# Use a slim JRE as the base image
FROM eclipse-temurin:21-jre-jammy

# Set the working directory inside the container
WORKDIR /app

# The application plugin builds a distributable version of your app.
# Copy the contents of that distribution into the container.
COPY build/install/Triceratops .

# The entrypoint is the script generated by the application plugin to run the app.
ENTRYPOINT ["/app/bin/Triceratops"]
